-- liquibase formatted sql changeLogId:1c4bd7db-bcb9-49e3-80a7-dc823a52bd0e

-- changeset kalbakry:1
CREATE TABLE "employees" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "employees_pk" PRIMARY KEY ("id"));
--rollback DROP TABLE employees;


-- changeset kalbakry:2
alter table employees add column name varchar(50)
--rollback ALTER TABLE employees DROP COLUMN name;

-- changeset kalbakry:3
alter table employees add column salary INTEGER
--rollback ALTER TABLE employees DROP COLUMN salary;